service: test-milio

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: production
  region: us-east-1
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 25
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_DATABASE: ${env:DB_DATABASE}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES: ${env:JWT_EXPIRES}

functions:
  api:
    handler: dist/serverless.handler
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: '/{proxy+}'

plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-dotenv-plugin
