service: test-milio

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: production
  region: us-east-1
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 25

functions:
  api:
    handler: dist/serverless.handler
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: '/{proxy+}'

plugins:
  - serverless-jetpack
  - serverless-offline
